# Generated by Django 6.0.6 on 2026-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='google_book_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
