# Generated by Django 6.0.6 on 2026-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
