# Generated by Django 6.0.6 on 2026-09-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_original_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('want_to_read', 'want to read'), ('currently_reading', 'currently reading'), ('read', 'Finished')], default='want_to_read', max_length=30),
        ),
    ]
