# Generated by Django 6.0.6 on 2026-06-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('adaptation_type', models.CharField(choices=[('movie', 'movie'), ('tv_show', 'TV Show')], default='movie', max_length=20)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('watch_status', models.CharField(choices=[('want_to_watch', 'Want to watch'), ('currently_watching', 'Currently watching'), ('watched', 'watched')], default='want_to_watch', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptations', to='books.book')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
