# Generated by Django 6.0.6 on 2026-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptations', '0002_adaptation_delete_adaptations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptation',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
