# Generated by Django 6.0.6 on 2026-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptations', '0003_alter_adaptation_rating'),
        ('books', '0003_book_cover_url_book_google_book_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptation',
            options={'ordering': ['-release_year', 'title']},
        ),
        migrations.RemoveField(
            model_name='adaptation',
            name='adaptation_type',
        ),
        migrations.RemoveField(
            model_name='adaptation',
            name='watch_status',
        ),
        migrations.AddField(
            model_name='adaptation',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adaptation',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV SHOW')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='adaptation',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adaptation',
            name='status',
            field=models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('currently_watching', 'Currently Watching'), ('watched', 'Watched')], default='want_to_watch', max_length=30),
        ),
        migrations.AlterField(
            model_name='adaptation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='adaptation',
            constraint=models.UniqueConstraint(fields=('book', 'title', 'media_type', 'release_year'), name='unique_adaptation_per_book'),
        ),
    ]
